// Generated by gencpp from file bag2orb/TatBry.msg
// DO NOT EDIT!


#ifndef BAG2ORB_MESSAGE_TATBRY_H
#define BAG2ORB_MESSAGE_TATBRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bag2orb
{
template <class ContainerAllocator>
struct TatBry_
{
  typedef TatBry_<ContainerAllocator> Type;

  TatBry_()
    : header()
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  TatBry_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::bag2orb::TatBry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bag2orb::TatBry_<ContainerAllocator> const> ConstPtr;

}; // struct TatBry_

typedef ::bag2orb::TatBry_<std::allocator<void> > TatBry;

typedef boost::shared_ptr< ::bag2orb::TatBry > TatBryPtr;
typedef boost::shared_ptr< ::bag2orb::TatBry const> TatBryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bag2orb::TatBry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bag2orb::TatBry_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bag2orb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'bag2orb': ['/home/b2256/catkin_ws/src/bag2orb/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bag2orb::TatBry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bag2orb::TatBry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bag2orb::TatBry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bag2orb::TatBry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bag2orb::TatBry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bag2orb::TatBry_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bag2orb::TatBry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8061e110314ddf08ca1dfbc48d314df8";
  }

  static const char* value(const ::bag2orb::TatBry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8061e110314ddf08ULL;
  static const uint64_t static_value2 = 0xca1dfbc48d314df8ULL;
};

template<class ContainerAllocator>
struct DataType< ::bag2orb::TatBry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bag2orb/TatBry";
  }

  static const char* value(const ::bag2orb::TatBry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bag2orb::TatBry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::bag2orb::TatBry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bag2orb::TatBry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TatBry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bag2orb::TatBry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bag2orb::TatBry_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAG2ORB_MESSAGE_TATBRY_H
