// Generated by gencpp from file obdii_interface/ObdiiState.msg
// DO NOT EDIT!


#ifndef OBDII_INTERFACE_MESSAGE_OBDIISTATE_H
#define OBDII_INTERFACE_MESSAGE_OBDIISTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace obdii_interface
{
template <class ContainerAllocator>
struct ObdiiState_
{
  typedef ObdiiState_<ContainerAllocator> Type;

  ObdiiState_()
    : header()
    , delay(0.0)
    , speed(0.0)
    , distance(0.0)
    , flags(0)  {
    }
  ObdiiState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , delay(0.0)
    , speed(0.0)
    , distance(0.0)
    , flags(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _delay_type;
  _delay_type delay;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _distance_type;
  _distance_type distance;

   typedef int32_t _flags_type;
  _flags_type flags;




  typedef boost::shared_ptr< ::obdii_interface::ObdiiState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obdii_interface::ObdiiState_<ContainerAllocator> const> ConstPtr;

}; // struct ObdiiState_

typedef ::obdii_interface::ObdiiState_<std::allocator<void> > ObdiiState;

typedef boost::shared_ptr< ::obdii_interface::ObdiiState > ObdiiStatePtr;
typedef boost::shared_ptr< ::obdii_interface::ObdiiState const> ObdiiStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obdii_interface::ObdiiState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obdii_interface::ObdiiState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obdii_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'obdii_interface': ['/home/b2256/catkin_ws/src/obdii_interface/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obdii_interface::ObdiiState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obdii_interface::ObdiiState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obdii_interface::ObdiiState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obdii_interface::ObdiiState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obdii_interface::ObdiiState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obdii_interface::ObdiiState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obdii_interface::ObdiiState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77d5ab65db3911553d2e7228c912a97d";
  }

  static const char* value(const ::obdii_interface::ObdiiState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77d5ab65db391155ULL;
  static const uint64_t static_value2 = 0x3d2e7228c912a97dULL;
};

template<class ContainerAllocator>
struct DataType< ::obdii_interface::ObdiiState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obdii_interface/ObdiiState";
  }

  static const char* value(const ::obdii_interface::ObdiiState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obdii_interface::ObdiiState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is the obdii message primitive.  Catkin builds out a header file from this.\n\
\n\
Header header\n\
float32 delay\n\
float32 speed\n\
float32 distance\n\
int32 flags\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::obdii_interface::ObdiiState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obdii_interface::ObdiiState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.delay);
      stream.next(m.speed);
      stream.next(m.distance);
      stream.next(m.flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObdiiState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obdii_interface::ObdiiState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obdii_interface::ObdiiState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "delay: ";
    Printer<float>::stream(s, indent + "  ", v.delay);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "flags: ";
    Printer<int32_t>::stream(s, indent + "  ", v.flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBDII_INTERFACE_MESSAGE_OBDIISTATE_H
